language: python3
python:
    - "3.0"

sudo: required
        
branches:
      - master
      - dps310
      - test

env:
   
       
    matrix:
        - PLATFORMIO_CI_SRC=examples/i2c_background
        - PLATFORMIO_CI_SRC=examples/i2c_command
        - PLATFORMIO_CI_SRC=examples/i2c_interrupt
        - PLATFORMIO_CI_SRC=examples/spi_background
        - PLATFORMIO_CI_SRC=examples/spi_command
        - PLATFORMIO_CI_SRC=examples/spi_interrupt

install:
    # build with stable core
    - pip install --upgrade pip
    - pip install -U platformio
    - platformio platform install -f infineonxmc

script:
    - platformio ci --lib="." --board=xmc1100_xmc2go --board=xmc1100_boot_kit --board=xmc4700_relax_kit --board=uno --board nodemcuv2

after_success:
    # only build once (after one job by checking id, however this does not work reliably)
    - |
      if [ $(($TRAVIS_JOB_ID - $TRAVIS_BUILD_ID)) -eq 2 ]; then
        export REPO_NAME=${TRAVIS_REPO_SLUG#*/}
        git clone https://github.com/Infineon/InfineonDoxyGenerator.git
        cd InfineonDoxyGenerator/docs
        chmod +x publish_pdf.sh
        ./publish_pdf.sh
      fi
