language: python
python:
    - 3.7

sudo: required

cache: pip
        
branches:
      - master
      - dps310
      - test

env:
   
       
    matrix:
        - PLATFORMIO_CI_SRC=examples/i2c_background
        - PLATFORMIO_CI_SRC=examples/i2c_command
        - PLATFORMIO_CI_SRC=examples/i2c_interrupt
        - PLATFORMIO_CI_SRC=examples/spi_background
        - PLATFORMIO_CI_SRC=examples/spi_command
        - PLATFORMIO_CI_SRC=examples/spi_interrupt

before_install:
  - python3 -m pip install -U coverage codecov mypy

install:
    # build with stable core    
    - pip install -U platformio
    - platformio platform install -f infineonxmc

script:
    -  platformio ci --lib="."  --board=xmc1100_xmc2go --board=xmc1100_boot_kit --board=xmc4700_relax_kit --board=uno --board nodemcuv2
    -  python3 -m coverage run ./examples/

after_success:
  - codecov

